### ISSUE TITLE
Design Pages with Figma

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#1]
Please check the Project plan document [here](https://docs.google.com/document/d/1lm2Z65vFMboWmQPP-8U0w0Iasy5dN9nd1jj1HpIZ3ko/edit) for the link to the Figma File under the RESOURCES section.
- [x] Landing: can have list of elections categorized into pending, ongoing & ended.
- [x] Add Election: a form to allow the user create a new election contract.
- [x] Election Detail: a user will view election and add candidate(s) and add voter(s).
- [x] Add Candidate: can be a form or a popup form to allow for adding a candidate.
- [x] Add Voter: can be a form or a popup form to allow for adding a voter.
- [x] Election Summary or Stats: for everyone to see the status of an election, very useful when election has ended.

**Comment by dr-winner** [comment]
@mikehammond 
I want to take part in this one... i only have figma installed

**Comment by mikehammond** [comment]
> @mikehammond I want to take part in this one... i only have figma installed

@dr-winner That is excellent.
I am working to get you a FIGMA Project for that

**Comment by mikehammond** [comment]
> @mikehammond I want to take part in this one... i only have figma installed

@dr-winner Please check the Project plan document [here](https://docs.google.com/document/d/1lm2Z65vFMboWmQPP-8U0w0Iasy5dN9nd1jj1HpIZ3ko/edit) for the link to the Figma File under the RESOURCES section.

**Comment by bernixCodes** [comment]
@mikehammond I want to design the Add Candidate page

**Comment by mikehammond** [comment]
> @mikehammond I want to design the Add Candidate page

@bernixCodes Please proceed.

**Comment by mikehammond** [comment]
@kelvin-codes @bernixCodes @dr-winner I am closing this issue as done now.
