### ISSUE TITLE
Develop the Header Component

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#15]
Please refer to our Figma **Hi-Fi** page for the screenshots below for the different variations of the header.

![image](https://github.com/user-attachments/assets/9ee605c0-50f0-4f85-bf81-5abc523231ed)
![image](https://github.com/user-attachments/assets/4227b440-e919-4a51-b5b0-67d20d7baa33)

- Work in the file **frontend/src/components/Header.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000 to see your changes at the very top.
- Raise a PR when done.

Dependencies
- #13

**Comment by kerimcanbalkan** [comment]
Taking up this issue, and I will work on it.

**Comment by mikehammond** [comment]
> Taking up this issue, and I will work on it.

@kerimcanbalkan Excited to have you take this one up.
