### ISSUE TITLE
Develop the Footer Component

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#16]
Please refer to our Figma **Hi-Fi** landing page for the screenshot below for the footer.

![image](https://github.com/user-attachments/assets/ae59b1ca-c5d3-46b4-a9aa-c4cbbe1596dc)

- Work in the file **frontend/src/components/Footer.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000 to see your changes at the very bottom.
- Raise a PR when done.

Dependencies
- #13

**Comment by mikehammond** [comment]
@Webnai Can you attend to this issue to complete how the Landing page shows?
If so please proceed and I will assign it to you.

**Comment by Webnai** [comment]
@mikehammond  yes I would be honored to handle it

**Comment by mikehammond** [comment]
@Webnai It's all yours.

**Comment by Webnai** [comment]
@mikehammond it's complete now please review
