### ISSUE TITLE
Initialize Blockchain Project using Hardhat

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#2]
- [ ] Create a folder named **blockchain** in the root of the project.
- [ ] `cd` into the **blockchain** folder.
- [ ] Follow the guide [here](https://hardhat.org/hardhat-runner/docs/guides/project-setup) to initialize the project. Please select the 2nd option (`Create a TypeScript project`).
- [ ] Please do not remove the boilerplate code in the project. Mainly `contracts/Lock.sol`, `tests/Lock.ts` & `ignition/modules/Lock.ts`. We will be using it as reference as we go.
- [ ] Commit and push your code(s) whiles you are at it.
- [ ] Raise a PR to be merged once ready.

**Comment by mickeymond** [comment]
@mikehammond I want to take up this issue.

**Comment by mikehammond** [comment]
> @mikehammond I want to take up this issue.

Sure thing @mickeymond I have assigned it to you.
Take it away.
Note that this issue is a dependency for all the blockchain issues so you need to go fast.
