### ISSUE TITLE
Develop the Add Voters Component

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#20]
Please refer to our Figma **Hi-Fi** page for the add voters component excluding the **header** and **footer**.

https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=256-641&t=WMH9AMr2CFxGZmz1-4 (1st State)
https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=256-720&t=WMH9AMr2CFxGZmz1-4 (2nd State)

- Work in the file **frontend/src/app/elections/[id]/voters/components/AddVoters.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000/elections/1/voters to see your changes.
- Raise a PR when done.

Dependencies
- #13

**Comment by Emmanuel-Darko** [comment]
@mikehammond 
I want to take this

**Comment by mikehammond** [comment]
@Emmanuel-Darko You got it

**Comment by mikehammond** [comment]
@Emmanuel-Darko Are you at a point of completing this so that I can do a quick refactor for the entire code base?

**Comment by mikehammond** [comment]
@Emmanuel-Darko Do you need any support on this one?

**Comment by Emmanuel-Darko** [comment]
Hello please I'll get it done by the close of business tomorrow.
I was a bit tight last week and on Sunday too, I couldn't join the meeting.
Please forgive me

**Comment by mikehammond** [comment]
@Emmanuel-Darko This is well noted

**Comment by Emmanuel-Darko** [comment]
@mikehammond 
Please can you expound the role of the import csv file for me?
![image](https://github.com/user-attachments/assets/58d6d51f-ade6-40f3-af51-452c51e9f87e)

Does the import automatically populate the form above with the imported addresses or we save the csv file when imported

**Comment by mikehammond** [comment]
@Emmanuel-Darko I think that we can put the control for the import there like you've done now and leave what it will be doing to be discussed later.

**Comment by Emmanuel-Darko** [comment]
@mikehammond 
Please I've created a PR
