### ISSUE TITLE
Develop the Election Contract

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#3]
Your working directory is **blockchain**.
- [x] Create an `Election.sol` file in the **contracts** folder.

Refer to our project plan [here](https://docs.google.com/document/d/1lm2Z65vFMboWmQPP-8U0w0Iasy5dN9nd1jj1HpIZ3ko/edit?usp=sharing) to develop the following functions for the Election contract.

- [x] `constructor()`: will take all the information at the time of creating the election contract.
- [x] `addCandidate()`: will add a new candidate to the election.
- [x] `getCandidates()`: get all candidates.
- [x] `addVoter()`: will add a voter to the election.
- [x] `getVoter()`: get a single voter by their UID (in our case their blockchain address).
- [x] `castVote()`: will allow a voter to cast their vote.
- [x] Develop any other extra functions that you can think off but be ready to justify the rationale behind them and also be willing to discard them if the rest of the team thinks otherwise.
- [x] Commit and push your code(s) whiles you are at it.
- [x] Raise a PR to be merged once ready.

Dependencies
- #2

**Comment by AngeloKwakye** [comment]
hello Mike, please id like to take this issue

**Comment by mikehammond** [comment]
> hello @mikehammond, please id like to take this issue

@AngeloKwakye You got it.
I have assigned it to you.

**Comment by Emmanuel-Darko** [comment]
Can I help on this too? @mikehammond

**Comment by mikehammond** [comment]
> Can I help on this too? @mikehammond

@Emmanuel-Darko If you want to help on this too then we have 2 options.
1. You work on yours from your end as well so that when you and @AngeloKwakye both raise your PRs, I will have to choose between 1 of them and ignore the other.
2. Or you and @AngeloKwakye will have to find a way to PAIR program. Maybe on a Google Meet call. The changes will be made from the device of only 1 of you by the way and the PR be raised by that very person.

So @Emmanuel-Darko How do you see this happening?
@AngeloKwakye Please feel free to also share your thoughts on this one.

**Comment by Emmanuel-Darko** [comment]
I will reach out to @AngeloKwakye and have a pair programming with him please @mikehammond

**Comment by AngeloKwakye** [comment]
@mikehammond i am also fine with the pair programming

**Comment by Emmanuel-Darko** [comment]
@AngeloKwakye 
Please give me your contact details

**Comment by AngeloKwakye** [comment]
@Sobee166 on telegram
