### ISSUE TITLE
Develop the Election Summary Page

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#33]
Please refer to our Figma **Hi-Fi** page https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=402-410&t=37C8a1yiJoCRKdGO-4

- Work in the file **frontend/src/app/elections/[id]/summary/page.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000/elections/1/summary to see your changes.
- Raise a PR when done.

**Comment by theGeniusDennis** [comment]
@mikehammond I would like to work on this

**Comment by Adama00** [comment]
This page is exclusively mine @theGeniusDennis

**Comment by theGeniusDennis** [comment]
Apologies @Adama00

**Comment by mikehammond** [comment]
@Adama00 I have assigned it to you.
