### ISSUE TITLE
Develop the Election Voting Link Page

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#34]
Please refer to our Figma **Hi-Fi** page https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=402-444&t=37C8a1yiJoCRKdGO-4

- Work in the file **frontend/src/app/elections/[id]/link/page.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000/elections/1/link to see your changes.
- Raise a PR when done.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Adama00** [comment]
Please, can I be assigned...

**Comment by mikehammond** [comment]
@Adama00 This has been assigned to you now.

**Comment by mikehammond** [comment]
@Adama00 How far are we getting with this one?
