### ISSUE TITLE
Develop the Check Voter Eligibility Page

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#36]
Please refer to our Figma **Hi-Fi** page https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=536-105&t=37C8a1yiJoCRKdGO-4

- Work in the file **frontend/src/app/elections/[id]/verify/page.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000/elections/1/verify to see your changes.
- Raise a PR when done.

**Comment by AngeloKwakye** [comment]
@mikehammond I'd like to take this issue

**Comment by mikehammond** [comment]
@AngeloKwakye Please take it away.

**Comment by mikehammond** [comment]
@AngeloKwakye That is very much okay

**Comment by AngeloKwakye** [comment]
@mikehammond i wanted to add a change event to handle the input data and all, but i can't use useState or useRef because of the Metadata interface

**Comment by mikehammond** [comment]
@AngeloKwakye Have you done something about it?
If not, I can make some changes to your code and push it back to you to proceed with that.

**Comment by AngeloKwakye** [comment]
I prefer you make the changes and push it back to me
