### ISSUE TITLE
Develop the Election Voting Page

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#37]
Please refer to our Figma **Hi-Fi** page https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=595-272&t=37C8a1yiJoCRKdGO-4

- Work in the file **frontend/src/app/elections/[id]/vote/page.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000/elections/1/vote to see your changes.
- Raise a PR when done.

**Comment by mikehammond** [comment]
@AngeloKwakye Are you up for this one?

**Comment by AngeloKwakye** [comment]
Yeah @mikehammond, absolutely 👍🏽

**Comment by mikehammond** [comment]
@AngeloKwakye You got it
