### ISSUE TITLE
Develop the Election Results Page

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#38]
Please refer to our Figma **Hi-Fi** page https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=626-602&t=37C8a1yiJoCRKdGO-4
The focus is on the ONGOING/OPEN state.

- Work in the file **frontend/src/app/elections/[id]/results/page.tsx** only.
- Locate your images to use in the **frontend/public/images**. Please do not rename any image.
- Visit the Landing at http://localhost:3000/elections/1/results to see your changes.
- Raise a PR when done.

**Comment by mikehammond** [comment]
@Webnai What do you say about taking up this issue?

**Comment by Webnai** [comment]
@mikehammond  sure I would grateful

**Comment by mikehammond** [comment]
@Webnai You got it.

**Comment by Webnai** [comment]
@mikehammond I would need to install a package called Nprogress for the progress bar do you concur or have further suggestions?

**Comment by mikehammond** [comment]
@Webnai I am okay with it but use the Next compatible one [here](https://www.npmjs.com/package/next-nprogress-bar).

**Comment by Webnai** [comment]
@mikehammond  the package recommended is not compatible and throws an error from the node modules after install or call

**Comment by mikehammond** [comment]
@Webnai Then let go with the one you suggested?
