### ISSUE TITLE
Implement Wallet Connection

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#39]
I want us to tone it down a bit to the beginner level and start with only wallet connection via metamask.
There is the Metamask SDK but since we are using React/Next.js we will use a very light weight package called [**metamask-react**](https://www.npmjs.com/package/metamask-react) to aid our development.

Please develop and test your work before pushing and raising a PR.

To understand more about Metamask and how to get the extension installed in your preferred browser, visit https://metamask.io/

**Comment by theGeniusDennis** [comment]
I would like to work on this! @mikehammond

**Comment by mikehammond** [comment]
@theGeniusDennis Are you having a good time with this issue or do you need some support?

**Comment by theGeniusDennis** [comment]
@mikehammond I wasn't able to do much last week with the task last week. 
I'll work on it within the week and if I face any difficulty, I'll let you know.

**Comment by mikehammond** [comment]
@theGeniusDennis Very well noted
