### ISSUE TITLE
Write Tests for the Election Contract

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#4]
Your working directory is **blockchain**.
- [x] Create an `Election.ts` file in the tests folder.
- [ ] Follow the guide [here](https://hardhat.org/hardhat-runner/docs/guides/test-contracts) to develop 100% coverage test for all the functions in the `Election.sol` contract.
- [x] Commit and push your code(s) whiles you are at it.
- [x] Raise a PR to be merged once ready.

Dependencies
- #3

**Comment by Emmanuel-Darko** [comment]
@mikehammond 
I want to tackle this

**Comment by mikehammond** [comment]
> @mikehammond I want to tackle this after review of the Election contract

Alright @Emmanuel-Darko 
I am going to review the issue #12 to see if it can be merged.

**Comment by mikehammond** [comment]
@Emmanuel-Darko The PR #12 has been merged so you can proceed to work on this issue.

**Comment by Emmanuel-Darko** [comment]
okay @mikehammond

**Comment by mikehammond** [comment]
@Emmanuel-Darko How is this issue going so far for you? Do you need any support?

**Comment by Emmanuel-Darko** [comment]
I've created a PR please @mikehammond
