### ISSUE TITLE
Modify Election Contract & Associated Tests

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#45]
Please work only in `Election.sol` in the contracts folder & `Election.ts` for the tests folder all in the blockchain folder.
- [x] Update the Candidate struct with the following fields: **team (string)** & **image (string)**.
- [x] Rename **hasVoted** field in the Voter struct to **voted** to avoid reading ambiguity.
- [x] Refactor error messages used in the require to custom solidity Errors.
- [x] Update the associated tests in the `Election.ts` accordingly to achieve 100% coverage.
- [x] Make any other optimizations that are needed and raise a PR

**Comment by mikehammond** [comment]
@Ratawine7 Are you up for this one?

**Comment by Ratawine7** [comment]
yh

**Comment by mikehammond** [comment]
@Ratawine7 It's all yours now.
Raise a PR when ready.

**Comment by Ratawine7** [comment]
some environment variables have been set.  Can you help me with that?

**Comment by mikehammond** [comment]
@Ratawine7 There are no environment variables that needs to be shared with you though.

**Comment by mikehammond** [comment]
@Ratawine7 I think I get you now.
Create a **.env** file in the Blockchain folder.
Then put a key `PRIVATE_KEY=your own testing private key`

**Comment by Ratawine7** [comment]
Hi Michael,

I've made some changes to the election contract and its corresponding test file. While I wasn't able to achieve 100% test coverage, I believe I've made significant improvements to the overall test suite.

Please review the changes and let me know if you have any questions or feedback.

Thanks

![Uploading Screenshot 2024-09-17 at 07.35.06.png…]()
