### ISSUE TITLE
Add a GitHub Workflow to Automate Smart Contract Testing

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#5]
- [ ] Read up on GitHub Action [here](https://docs.github.com/en/actions).
- [ ] Delve into an example testing workflow for Node.js [here](https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs).
- [ ] Get more understanding from a similar/same workflow we can actually copy and use [here](https://github.com/mowblox/emt-marketplace/blob/main/.github/workflows/blockchain-ci.yaml).
- [ ] Put together our workflow.
- [ ] Commit and push your code(s) whiles you are at it.
- [ ] Raise a PR to be merged once ready.

Dependencies
- #2

**Comment by mickeymond** [comment]
@mikehammond Can I take this one up?

**Comment by mikehammond** [comment]
> @mikehammond Can I take this one up?

@mickeymond Please take it away.
