### ISSUE TITLE
Shorten Connected Address to Match Conventional Practice

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#51]

**Comment by Emmanuel-Darko** [comment]
@mikehammond 
Can I take this?

**Comment by mikehammond** [comment]
@Emmanuel-Darko Please go ahead

**Comment by mikehammond** [comment]
@Emmanuel-Darko I am coming back to say we have to discard this issue again now because I have now replaced the MetaMask connection package with [@metamask/sdk-react-ui](https://docs.metamask.io/wallet/how-to/use-sdk/javascript/react/react-ui/) and it has added this very behavior to the button.

**Comment by mikehammond** [comment]
![image](https://github.com/user-attachments/assets/38ba7020-c98c-4377-b99f-f605ed706723)

**Comment by Emmanuel-Darko** [comment]
Noted please

Regards
