### ISSUE TITLE
Develop the Election List View

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#57]
Link to Figma Design: https://www.figma.com/design/aJGE4crhpDJQnfH7ppH5vV/ABVS-UI?node-id=1327-170&t=Wh1ymdrf5OIQWJF4-4
- Visit https://localhost:3000/elections and Connect your wallet.
- We need a more appealing list/tile view instead of the list of addresses that are currently been shown on the page.
- Even if you are not able to do the smart contract integration, give us an appealing UI based on the current look of the application.

**Comment by Webnai** [comment]
@mikehammond can I take this issue

**Comment by mikehammond** [comment]
@Webnai Did you say you wanted to take this one?

**Comment by Webnai** [comment]
@mikehammond yes can I?

**Comment by mikehammond** [comment]
@Webnai When you run the app you will see that there is already some data from the blockchain getting displayed but not in a nice way so take it from there.
Your Metamask should be connected to Sepolia Network

**Comment by Webnai** [comment]
well noted sir
