### ISSUE TITLE
Develop the Election Factory Contract

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#6]
Your working directory is **blockchain**.
- [x] Create an `ElectionFactory.sol` file in the **contracts** folder.

Refer to our project plan [here](https://docs.google.com/document/d/1lm2Z65vFMboWmQPP-8U0w0Iasy5dN9nd1jj1HpIZ3ko/edit?usp=sharing) to develop the following functions for the Election Factory contract.

- [x] `createElection()`: will be called to create a new instance of the Election contract.
- [x] `getElections()`: returns all elections that have been created so far.
- [x] Develop any other extra functions that you can think off but be ready to justify the rationale behind them and also be willing to discard them if the rest of the team thinks otherwise.
- [x] Commit and push your code(s) whiles you are at it.
- [x] Raise a PR to be merged once ready.

Dependencies
- #3

**Comment by theGeniusDennis** [comment]
@mikehammond   I would please like to work this.

**Comment by mikehammond** [comment]
>  @mikehammond   I would please like to work on this.
>  

@theGeniusDennis You got it.

**Comment by theGeniusDennis** [comment]
> > @mikehammond   I would please like to work on this.
> 
> @theGeniusDennis You got it.

yes sir! @mikehammond

**Comment by Emmanuel-Darko** [comment]
@mikehammond 
Please what's the difference between Election Contract and the Election Factory?
I'm a bit confused

**Comment by mikehammond** [comment]
@Emmanuel-Darko Election Factory will be used to create many instances of the Election when a user decides to add election on the Frontend

**Comment by mikehammond** [comment]
@Emmanuel-Darko Election Factory will be used to create many instances of the Election when a user decides to add election on the Frontend.
