### ISSUE TITLE
Figma: Design All Elections Page

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#64]
There is a page at https://abvs.vercel.app/elections that we need a design for to display all the elections created on the platform either in  List or Table View.
Please capture the following,
- [x] Top Search Bar to enable searching over the elections using keywords
- [x] Filtering and/or Sorting controls
- [x] List / Table View to display Elections

**Comment by dr-winner** [comment]
I’ll it take up

**Comment by mikehammond** [comment]
@dr-winner Please take it away

**Comment by mikehammond** [comment]
@kelvin-codes @dr-winner Thank you very much for the effort
