### ISSUE TITLE
Write Tests for the Election Factory Contract

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#7]
Your working directory is **blockchain**.
- [ ] Create an `ElectionFactory.ts` file in the tests folder.
- [ ] Follow the guide [here](https://hardhat.org/hardhat-runner/docs/guides/test-contracts) to develop 100% coverage test for all the functions in the `ElectionFactory.sol` contract.
- [ ] Commit and push your code(s) whiles you are at it.
- [ ] Raise a PR to be merged once ready.

Dependencies
- #6

**Comment by Emmanuel-Darko** [comment]
@mikehammond 
I want to tackle this

**Comment by Ratawine7** [comment]
Please I want to handle this issue.

**Comment by mikehammond** [comment]
@Ratawine7 I will assign it to you once #6 is done and merged.

**Comment by mikehammond** [comment]
@Ratawine7 This issue is all yours now.

**Comment by mikehammond** [comment]
@Ratawine7 How is this ticket coming up?

**Comment by Ratawine7** [comment]
I just wanted to let you know that I'm done with it.
I am facing a permission issue to push but I will resolve it as soon as possible and update you.
thanks for the follow-up

**Comment by mikehammond** [comment]
@Ratawine7 But have you figured out why you are facing the permission issue?

**Comment by Ratawine7** [comment]
Yeah. one of my repos takes precedence over the forked. making the changes

**Comment by Ratawine7** [comment]
I raised PR
