### ISSUE TITLE
Setup Frontend Project with Next.js & TypeScript

### ISSUE THREAD

**Issue by mikehammond** [mowblox/auditable-blockchain-voting-system#9]
Follow the automatic installation guide [here](https://nextjs.org/docs/getting-started/installation).
We are going to be using **Tailwind CSS** so take **YES** for that option as well.
- [x] Ensure project ends up in a folder named `frontend` at the root of the project.
- [x] Project name should be `frontend`.
- [x] Select **YES** for all the questions asked.
- [x] Commit and push your code(s) whiles you are at it.
- [x] Raise a PR to be merged once ready.

**Comment by theGeniusDennis** [comment]
@mikehammond I would like to work on this issue.

**Comment by mikehammond** [comment]
> @mikehammond I would like to work on this issue.

@theGeniusDennis You got it.
Waiting for a PR once ready.

**Comment by theGeniusDennis** [comment]
Yes sir! @mikehammond

**Comment by theGeniusDennis** [comment]
> > @mikehammond I would like to work on this issue.
> 
> @theGeniusDennis You got it. Waiting for a PR once ready.

Yes sir! @mikehammond
